format: "yaml"
output_dir: "./reports"
providers:
  - name: gitlab # or github
    token: "gl***"
    base_url: "https://gitlab.com"
    lookback_hours: 96
    state: "all" # closed, open
    authors:
      - bob
      - alice
    repos:
      - foo/bar
      - baz/*
